### ISSUE TITLE
Filter for all items with custom sort

### ISSUE THREAD

**Issue by palortoff** [palortoff/d3-item-manager#19]
All Level 70 Legendary + Set Items

Ordered by Type and Class

I do it since years manually with an Excel Sheet I save as html to add the Tooltip informations
Its nesassary for a good overview, I dont want to click 20 times though all filters. In addition your Filter Funktion is much slower than Strg+F in the browser if you can see all items. On your Filter funktion you have to scroll up, click in the Field and write

Would be nice if you could add the funktion with a good order overview sortable for Slot + Class, than I can dump my Excel work and alot of peoples would thank you

**Comment by prusswan** [comment]
I guess this means we can sort by Sword/Dagger etc (1 hander is not specific enough)
