### ISSUE TITLE
add support for Chinese Simplified (cn)

### ISSUE THREAD

**Issue by prusswan** [palortoff/d3-item-manager#36]

**Comment by palortoff** [comment]
as the D3 api does not provide the necessary data, I'm afraid I cannot do that...

**Comment by prusswan** [comment]
It does, which api are you using?

**Comment by palortoff** [comment]
I'm using the api at dev.battle.net

Aaaand I just found the CN data. The documentation structure was a bit confusing.
I'll check it out.

If it works, it will be part of the upcoming season 5 update.

**Comment by palortoff** [comment]
Done with 1.6.2

**Comment by prusswan** [comment]
:+1: 
I will host a mirror that defaults to cn locale, if you don't mind

**Comment by palortoff** [comment]
Sure, go ahead.

**Comment by palortoff** [comment]
Why do you need cn default? language settings are persistent.
