### ISSUE TITLE
Missing 'Halo of Karina' ring

### ISSUE THREAD

**Issue by IcyWynter** [palortoff/d3-item-manager#54]
http://us.battle.net/d3/en/item/halo-of-karini

yes Cubable

Don't remember where I found the ring

Thanks.

**Comment by palortoff** [comment]
I'm sorry, this project is discontinued.

patch 2.4 / Season 5 were the last updates.
I'll put a note on the readme...

You are welcome to fork and continue.

**Comment by IcyWynter** [comment]
ahh! I didnt know it was discontinued. that is too bad. It is excellent website. Thank you for your hard work on it tho!
